from flask import Flask, render_template, request, send_file
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import PyPDF2
import docx
import os
import wikipedia

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Table, TableStyle, ListFlowable, ListItem
)
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4

app = Flask(__name__)

# ✅ Increase upload size (20MB)
app.config['MAX_CONTENT_LENGTH'] = 20 * 1024 * 1024

# Ensure static folder exists
if not os.path.exists("static"):
    os.makedirs("static")

# -------------------------
# Wikipedia Role Mapping
# -------------------------
wiki_mapping = {
    "Data Scientist": "Data science",
    "Web Developer": "Web developer",
    "Software Engineer": "Software engineering"
}

# -------------------------
# Fetch Job Description from Wikipedia
# -------------------------
def get_job_description_from_wikipedia(role, level):
    try:
        page_name = wiki_mapping.get(role, role)
        summary = wikipedia.summary(page_name, sentences=5)

        if level == "Fresher":
            level_text = (
                "Entry-level candidate expected to have strong fundamentals, "
                "academic knowledge, and basic project experience."
            )
        else:
            level_text = (
                "Candidate expected to have real-world experience, "
                "industry exposure, system design knowledge, and project leadership."
            )

        return summary + "\n\n" + level_text

    except Exception:
        return "Professional technical role requiring analytical thinking and problem-solving skills."

# -------------------------
# Resume Text Extraction
# -------------------------
def extract_text_from_pdf(file):
    reader = PyPDF2.PdfReader(file)
    text = ""
    for page in reader.pages:
        text += page.extract_text() or ""
    return text


def extract_text_from_docx(file):
    document = docx.Document(file)
    return "\n".join([para.text for para in document.paragraphs])

# -------------------------
# PDF Report Generator
# -------------------------
def generate_report(score, role, level, missing_keywords):
    file_path = "static/report.pdf"
    doc = SimpleDocTemplate(file_path, pagesize=A4)
    elements = []
    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.textColor = colors.HexColor("#2E86C1")

    score_style = ParagraphStyle(
        name="ScoreStyle",
        parent=styles["Heading2"],
        fontSize=20,
        textColor=colors.green if score >= 70 else
                  colors.orange if score >= 40 else
                  colors.red
    )

    elements.append(Paragraph("Resume Analysis Report", title_style))
    elements.append(Spacer(1, 0.3 * inch))

    info_data = [
        ["Role Applied:", role],
        ["Experience Level:", level],
        ["Match Score:", f"{score}%"]
    ]

    table = Table(info_data, colWidths=[2.5 * inch, 3.5 * inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
    ]))

    elements.append(table)
    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph(f"Overall Match Score: {score}%", score_style))
    elements.append(Spacer(1, 0.4 * inch))

    elements.append(Paragraph("Missing Skills Identified:", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))

    if missing_keywords:
        skill_list = [ListItem(Paragraph(skill, styles["Normal"])) for skill in missing_keywords]
        elements.append(ListFlowable(skill_list, bulletType='bullet'))
    else:
        elements.append(Paragraph("No major skills missing. Excellent alignment!", styles["Normal"]))

    elements.append(Spacer(1, 0.4 * inch))
    elements.append(Paragraph("Generated by Resume AI Matcher Pro", styles["Normal"]))

    doc.build(elements)
    return file_path

# -------------------------
# Download Route
# -------------------------
@app.route('/download')
def download_report():
    return send_file("static/report.pdf", as_attachment=True)

# -------------------------
# Main Route
# -------------------------
@app.route('/', methods=['GET', 'POST'])
def index():
    score = None
    missing_keywords = []
    report_ready = False

    if request.method == 'POST':

        selected_role = request.form.get('role')
        selected_level = request.form.get('level')
        resume_file = request.files.get('resume')

        # Safety checks
        if not selected_role or not selected_level:
            return "Role or Experience Level not selected"

        if not resume_file or resume_file.filename == "":
            return "No file uploaded"

        # Get dynamic job description
        job_description = get_job_description_from_wikipedia(selected_role, selected_level)

        # Extract resume text
        if resume_file.filename.endswith('.pdf'):
            resume_text = extract_text_from_pdf(resume_file)
        elif resume_file.filename.endswith('.docx'):
            resume_text = extract_text_from_docx(resume_file)
        else:
            resume_text = resume_file.read().decode('utf-8', errors='ignore')

        # Similarity calculation
        text_data = [resume_text, job_description]
        cv = CountVectorizer(stop_words='english')
        matrix = cv.fit_transform(text_data)
        similarity = cosine_similarity(matrix)[0][1]

        score = round(similarity * 100, 2)

        resume_words = set(resume_text.lower().split())
        job_words = set(job_description.lower().split())
        missing_keywords = list(job_words - resume_words)[:10]

        generate_report(score, selected_role, selected_level, missing_keywords)
        report_ready = True

    return render_template("index.html",
                           score=score,
                           missing_keywords=missing_keywords,
                           report_ready=report_ready)

# -------------------------
# Run App
# -------------------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port)